### ISSUE TITLE
new account can not be found #2

### ISSUE THREAD

**Issue by engelhard61** [Capricoinofficial/copay#4] opened 2020-06-17 15:11 UTC
Hello,
thanks for answer for my first issue  a few hours ago.
I tried to restore the wallet from the backup, but it doesn´t matter.
There is a note: error wallet recovery phrase not valid. 
I´m sure the recovery phrase is correct. What can I do to restore my account ?

Is there any chance to import the wallet with the CPC on it ?

I had a Login password .

Thanks for anwer

Regards

Roland Engelhard

**Comment by CapricoinPlus** [comment] 2020-06-18 11:15
Duplicate of #3

**Closed as completed by CapricoinPlus** 2020-06-18 11:15 UTC
